### ISSUE TITLE
Umbrella Ticket

### ISSUE THREAD

**Issue by Giustanthony** [PedroBMedeiros/P2-Anteaters#18]
Kenzie
- [ ] Completed weekly ticket
- [ ] Created new ticket 

Pedro
- [ ] Completed weekly ticket
- [ ] Created new ticket 

Anthony
- [ ] Completed weekly ticket
- [ ] Created new ticket 

Naweid
- [ ] Completed weekly ticket
- [ ] Created new ticket 

Cherry
- [ ] Completed weekly ticket
- [ ] Created new ticket
